### ISSUE TITLE
Feature Request:  Transmogs for cross-armor type

### ISSUE THREAD

**Issue by Aldori15** [almeric1984/ezCollectionsHelper#3]
Would it be possible to implement the ability to learn transmogs for different armor types?  For example, playing on a Plate character can learn transmogs for Cloth or Leather when they are looted.  

Instead of only Plate-->Plate, Mail-->Mail, Leather-->Leather, Cloth-->Cloth.

**Comment by almeric1984** [comment]
This tool don't control what collections you earn. Mod-transmog is what does that. All this does is allows the addon to work with the mod

**Comment by Aldori15** [comment]
Okay gotcha.  I added this to the mod-transmog repo and will close this one out.  Thanks!
